### ISSUE TITLE
a bug when use in libtorch 1.7.1 version

### ISSUE THREAD

**Issue by happyboyneu** [wsx000/YOLOv4-LibTorch-GPU#1]
![image](https://user-images.githubusercontent.com/28706662/110201893-7227a500-7ea0-11eb-8a62-0e33e98aef49.png)
line 125 in yolo.cpp,there should be a parentheses before .unsqueeze(-1).
like this
![image](https://user-images.githubusercontent.com/28706662/110201959-c9c61080-7ea0-11eb-934d-ef0ed340aaf3.png)

**Comment by wsx000** [comment]
thanks for your discovery! I have corrected it
