### ISSUE TITLE
maybe a bug

### ISSUE THREAD

**Issue by happyboyneu** [wsx000/YOLOv4-LibTorch-GPU#2]
![image](https://user-images.githubusercontent.com/28706662/110287681-e2a9ff80-8021-11eb-863e-84cb6b1a920a.png)
in utils.cpp,this line will lead an error.
because  at::unique_consecutive is "Eliminates all but the first element from every consecutive group of equivalent elements.".
Not same with torch.unique().

**Comment by wsx000** [comment]
thanks！you are right！I  have found that the classes i get from this code only have one kind recently，But I never figured out what the problem was. now i think the problem is just as you said。But I haven't found the right function yet, Do you have a solution?

**Comment by happyboyneu** [comment]
看你的readme应该是中国人吧，直接中文回复了，libtorch里面没找到torch.unique()对应的实现，所以在遍历类别的时候，我直接使用了num_class。
![image](https://user-images.githubusercontent.com/28706662/110341689-94b6eb00-8065-11eb-81a2-d7b82cff298a.png)
有个限制就是要求类别id是从0开始连续的

**Comment by wsx000** [comment]
哎都是中国人早说嘛哈哈，终于找到之前的问题所在了，你这个思路确实可以，感谢提醒！
